//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.MasterData.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dict_ButtonInfo
    {
        public int ButtonID { get; set; }
        public string ButtonName { get; set; }
        public string ButtonValue { get; set; }
        public string ButtonJavascript { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public string IconName { get; set; }
        public Nullable<int> IndexCode { get; set; }
    }
}
