//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.MasterData.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_ProductOKCPriceInfo
    {
        public int ProductOKCPriceInfoID { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
        public Nullable<int> OKCID { get; set; }
        public Nullable<decimal> ProductOKCPrice { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        public virtual master_OKCInfo master_OKCInfo { get; set; }
        public virtual master_ProductInfo master_ProductInfo { get; set; }
    }
}
