//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.MasterData.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public master_UserInfo()
        {
            this.master_FeedbackStat = new HashSet<master_FeedbackStat>();
            this.master_MessageStat = new HashSet<master_MessageStat>();
            this.master_UserCustomerAuthority = new HashSet<master_UserCustomerAuthority>();
            this.master_UsersStat = new HashSet<master_UsersStat>();
            this.master_AreaInfo = new HashSet<master_AreaInfo>();
            this.master_DistributorInfo = new HashSet<master_DistributorInfo>();
            this.master_RoleInfo = new HashSet<master_RoleInfo>();
        }
    
        public int UserID { get; set; }
        public Nullable<int> DepartID { get; set; }
        public string UserCode { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public string DynamicPassword { get; set; }
        public Nullable<System.DateTime> EffectiveTtime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public string Email { get; set; }
        public Nullable<short> UserType { get; set; }
        public string AuditName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> NoActiveTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        public virtual master_DepartmentInfo master_DepartmentInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<master_FeedbackStat> master_FeedbackStat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<master_MessageStat> master_MessageStat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<master_UserCustomerAuthority> master_UserCustomerAuthority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<master_UsersStat> master_UsersStat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<master_AreaInfo> master_AreaInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<master_DistributorInfo> master_DistributorInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<master_RoleInfo> master_RoleInfo { get; set; }
    }
}
