//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.MasterData.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DepartToRegion
    {
        public string RegionName { get; set; }
        public int RegionID { get; set; }
        public string districtname { get; set; }
        public int districtid { get; set; }
        public string AreaName { get; set; }
        public int AreaID { get; set; }
        public string DepartName { get; set; }
        public int DepartID { get; set; }
    }
}
