//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Fcpa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class common_WarningInfo
    {
        public System.Guid WarningID { get; set; }
        public string BelongModule { get; set; }
        public Nullable<System.Guid> MappingID { get; set; }
        public string WarningInfo { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
