//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Fcpa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class common_LogInfo
    {
        public long LogIndex { get; set; }
        public string BelongModel { get; set; }
        public string BelongFunc { get; set; }
        public string LogDetails { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string OpratorName { get; set; }
    }
}
