//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Fcpa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dict_Structure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dict_Structure()
        {
            this.master_RoleAuthority = new HashSet<master_RoleAuthority>();
            this.master_UserCustomerAuthority = new HashSet<master_UserCustomerAuthority>();
        }
    
        public string StructureID { get; set; }
        public string ParentStructureID { get; set; }
        public string StructureName { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<int> IndexCode { get; set; }
        public string URL { get; set; }
        public Nullable<int> BelongButton { get; set; }
        public string DesImage { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<master_RoleAuthority> master_RoleAuthority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<master_UserCustomerAuthority> master_UserCustomerAuthority { get; set; }
    }
}
