//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Fcpa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fcpa_CredentialInfo
    {
        public System.Guid ID { get; set; }
        public string DistributorID { get; set; }
        public string Certificate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<bool> OffWork { get; set; }
        public Nullable<System.DateTime> OffWorkDate { get; set; }
        public Nullable<bool> Domain1 { get; set; }
        public Nullable<bool> Domain2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string Remark { get; set; }
    
        public virtual fcpa_DistributorInfo fcpa_DistributorInfo { get; set; }
    }
}
