//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Fcpa.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TCDMS_FCPAEntities : DbContext
    {
        public TCDMS_FCPAEntities()
            : base("name=TCDMS_FCPAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fcpa_AlarmInfo> fcpa_AlarmInfo { get; set; }
        public virtual DbSet<fcpa_CredentialInfo> fcpa_CredentialInfo { get; set; }
        public virtual DbSet<fcpa_DistributorInfo> fcpa_DistributorInfo { get; set; }
        public virtual DbSet<fcpa_UserInfo> fcpa_UserInfo { get; set; }
    }
}
