//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Fcpa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fcpa_UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fcpa_UserInfo()
        {
            this.fcpa_AlarmInfo = new HashSet<fcpa_AlarmInfo>();
        }
    
        public int UserID { get; set; }
        public Nullable<int> DepartID { get; set; }
        public string UserCode { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public string DynamicPassword { get; set; }
        public Nullable<System.DateTime> EffectiveTtime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public string Email { get; set; }
        public Nullable<short> UserType { get; set; }
        public string AuditName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> NoActiveTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string RelEmail { get; set; }
        public Nullable<bool> Domain1 { get; set; }
        public Nullable<bool> Domain2 { get; set; }
        public Nullable<int> Role { get; set; }
        public string RelDistributor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fcpa_AlarmInfo> fcpa_AlarmInfo { get; set; }
    }
}
