//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Fcpa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fcpa_DistributorInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fcpa_DistributorInfo()
        {
            this.fcpa_CredentialInfo = new HashSet<fcpa_CredentialInfo>();
        }
    
        public string DistributorID { get; set; }
        public string DistributorName { get; set; }
        public string AreaName { get; set; }
        public string RegionName { get; set; }
        public string OrgMap { get; set; }
        public string OrgMapFile { get; set; }
        public string Trains { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> OrgMapUpdateTime { get; set; }
        public Nullable<System.DateTime> TrainsUpdateTime { get; set; }
        public Nullable<int> ValidNum { get; set; }
        public Nullable<int> ShouldNum { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<bool> Domain1 { get; set; }
        public Nullable<bool> Domain2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fcpa_CredentialInfo> fcpa_CredentialInfo { get; set; }
    }
}
