//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Fcpa.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TCDMS_MasterDataEntities : DbContext
    {
        public TCDMS_MasterDataEntities()
            : base("name=TCDMS_MasterDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<common_AttachFileInfo> common_AttachFileInfo { get; set; }
        public virtual DbSet<common_LogInfo> common_LogInfo { get; set; }
        public virtual DbSet<common_WarningInfo> common_WarningInfo { get; set; }
        public virtual DbSet<dict_ButtonInfo> dict_ButtonInfo { get; set; }
        public virtual DbSet<dict_RegionInfo> dict_RegionInfo { get; set; }
        public virtual DbSet<dict_Structure> dict_Structure { get; set; }
        public virtual DbSet<imp_CustomerInfo> imp_CustomerInfo { get; set; }
        public virtual DbSet<master_AccountDateInfo> master_AccountDateInfo { get; set; }
        public virtual DbSet<master_AreaInfo> master_AreaInfo { get; set; }
        public virtual DbSet<master_AreaRegionInfo> master_AreaRegionInfo { get; set; }
        public virtual DbSet<master_CustomerApplyInfo> master_CustomerApplyInfo { get; set; }
        public virtual DbSet<master_CustomerInfo> master_CustomerInfo { get; set; }
        public virtual DbSet<master_DepartmentInfo> master_DepartmentInfo { get; set; }
        public virtual DbSet<master_DistributorADInfo> master_DistributorADInfo { get; set; }
        public virtual DbSet<master_DistributorInfo> master_DistributorInfo { get; set; }
        public virtual DbSet<master_DistributorOKCInfo> master_DistributorOKCInfo { get; set; }
        public virtual DbSet<master_DistributorPayInfo> master_DistributorPayInfo { get; set; }
        public virtual DbSet<master_DistributorProductLineInfo> master_DistributorProductLineInfo { get; set; }
        public virtual DbSet<master_DistributorRegionInfo> master_DistributorRegionInfo { get; set; }
        public virtual DbSet<master_DistributorServiceType> master_DistributorServiceType { get; set; }
        public virtual DbSet<master_DistributorTransport> master_DistributorTransport { get; set; }
        public virtual DbSet<master_DistributorType> master_DistributorType { get; set; }
        public virtual DbSet<master_FeedbackStat> master_FeedbackStat { get; set; }
        public virtual DbSet<master_InstrumentType> master_InstrumentType { get; set; }
        public virtual DbSet<master_MessageStat> master_MessageStat { get; set; }
        public virtual DbSet<master_OKCInfo> master_OKCInfo { get; set; }
        public virtual DbSet<master_PaymentInfo> master_PaymentInfo { get; set; }
        public virtual DbSet<master_ProductInfo> master_ProductInfo { get; set; }
        public virtual DbSet<master_ProductLine> master_ProductLine { get; set; }
        public virtual DbSet<master_ProductModel> master_ProductModel { get; set; }
        public virtual DbSet<master_ProductOKCPriceInfo> master_ProductOKCPriceInfo { get; set; }
        public virtual DbSet<master_ProductPriceInfo> master_ProductPriceInfo { get; set; }
        public virtual DbSet<master_ProductSmallType> master_ProductSmallType { get; set; }
        public virtual DbSet<master_ProductType> master_ProductType { get; set; }
        public virtual DbSet<master_RateInfo> master_RateInfo { get; set; }
        public virtual DbSet<master_RoleAuthority> master_RoleAuthority { get; set; }
        public virtual DbSet<master_RoleInfo> master_RoleInfo { get; set; }
        public virtual DbSet<master_TransportInfo> master_TransportInfo { get; set; }
        public virtual DbSet<master_UserCustomerAuthority> master_UserCustomerAuthority { get; set; }
        public virtual DbSet<master_UserInfo> master_UserInfo { get; set; }
        public virtual DbSet<master_UsersStat> master_UsersStat { get; set; }
    }
}
