//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Fcpa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_FeedbackStat
    {
        public int FeedbackStatID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        public Nullable<short> FeedbackStaus { get; set; }
        public string FeedbackSystem { get; set; }
        public string FeedbackModel { get; set; }
        public string FeedbackContent { get; set; }
        public string DealUser { get; set; }
        public Nullable<System.DateTime> DealDatetime { get; set; }
    
        public virtual master_UserInfo master_UserInfo { get; set; }
    }
}
