//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Fcpa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_AccountDateInfo
    {
        public int AccountDateID { get; set; }
        public string AccountDateName { get; set; }
        public Nullable<short> AccountDateYear { get; set; }
        public string AccountDatePlace { get; set; }
        public string AccountDateBelongModel { get; set; }
        public Nullable<System.DateTime> MonthDate { get; set; }
        public Nullable<System.DateTime> FebDate { get; set; }
        public Nullable<System.DateTime> MarchDate { get; set; }
        public Nullable<System.DateTime> AprilDate { get; set; }
        public Nullable<System.DateTime> MayDate { get; set; }
        public Nullable<System.DateTime> JuneDate { get; set; }
        public Nullable<System.DateTime> JulyDate { get; set; }
        public Nullable<System.DateTime> AugustDate { get; set; }
        public Nullable<System.DateTime> SepDate { get; set; }
        public Nullable<System.DateTime> OctDate { get; set; }
        public Nullable<System.DateTime> NovDate { get; set; }
        public Nullable<System.DateTime> DecDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    }
}
