//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Fcpa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_PaymentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public master_PaymentInfo()
        {
            this.master_DistributorPayInfo = new HashSet<master_DistributorPayInfo>();
        }
    
        public int PayID { get; set; }
        public string PayName { get; set; }
        public string OracleName { get; set; }
        public Nullable<System.DateTime> PayStartTime { get; set; }
        public Nullable<System.DateTime> PayEndTime { get; set; }
        public Nullable<bool> PayStatus { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<master_DistributorPayInfo> master_DistributorPayInfo { get; set; }
    }
}
