//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Fcpa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_ProductPriceInfo
    {
        public int ProductPriceID { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
        public Nullable<decimal> DNPPrice { get; set; }
        public Nullable<System.DateTime> DNPPriceStart { get; set; }
        public Nullable<System.DateTime> DNPPriceEnd { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        public virtual master_ProductInfo master_ProductInfo { get; set; }
    }
}
