//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Document.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Cts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document_Cts()
        {
            this.Document_CtsAttachmentDownload = new HashSet<Document_CtsAttachmentDownload>();
            this.Document_CtsFavorite = new HashSet<Document_CtsFavorite>();
        }
    
        public System.Guid CtsID { get; set; }
        public Nullable<System.Guid> TagID { get; set; }
        public string ProductNo { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> EffectDate { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public string Publisher { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public string AttachmentName { get; set; }
        public Nullable<int> AttachmentSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document_CtsAttachmentDownload> Document_CtsAttachmentDownload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document_CtsFavorite> Document_CtsFavorite { get; set; }
        public virtual Document_CtsTag Document_CtsTag { get; set; }
    }
}
