//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Document.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Register
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document_Register()
        {
            this.Document_RegisterAttachment = new HashSet<Document_RegisterAttachment>();
        }
    
        public System.Guid RegisterID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public string ProductTypeName { get; set; }
        public Nullable<int> ProductLineID { get; set; }
        public string ProductLineName { get; set; }
        public string ProductNo { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public string Publisher { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> PublisherID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document_RegisterAttachment> Document_RegisterAttachment { get; set; }
    }
}
