//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Document.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_CtsFavorite
    {
        public System.Guid FavoriteID { get; set; }
        public System.Guid CtsID { get; set; }
        public int UserID { get; set; }
        public System.DateTime FavoriteDate { get; set; }
    
        public virtual Document_Cts Document_Cts { get; set; }
    }
}
