//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Document.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TCDMS_DocumentEntities : DbContext
    {
        public TCDMS_DocumentEntities()
            : base("name=TCDMS_DocumentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Document_Bcce> Document_Bcce { get; set; }
        public virtual DbSet<Document_BcceAttachment> Document_BcceAttachment { get; set; }
        public virtual DbSet<Document_BcceAttachmentDownload> Document_BcceAttachmentDownload { get; set; }
        public virtual DbSet<Document_Cts> Document_Cts { get; set; }
        public virtual DbSet<Document_CtsAttachment> Document_CtsAttachment { get; set; }
        public virtual DbSet<Document_CtsAttachmentDownload> Document_CtsAttachmentDownload { get; set; }
        public virtual DbSet<Document_CtsFavorite> Document_CtsFavorite { get; set; }
        public virtual DbSet<Document_CtsTag> Document_CtsTag { get; set; }
        public virtual DbSet<Document_Lss> Document_Lss { get; set; }
        public virtual DbSet<Document_LssAttachment> Document_LssAttachment { get; set; }
        public virtual DbSet<Document_LssAttachmentDownload> Document_LssAttachmentDownload { get; set; }
        public virtual DbSet<Document_LssFavorite> Document_LssFavorite { get; set; }
        public virtual DbSet<Document_LssTag> Document_LssTag { get; set; }
        public virtual DbSet<Document_Register> Document_Register { get; set; }
        public virtual DbSet<Document_RegisterAttachment> Document_RegisterAttachment { get; set; }
        public virtual DbSet<Document_RegisterAttachmentDownload> Document_RegisterAttachmentDownload { get; set; }
    }
}
