//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Document.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_AreaRegionInfo
    {
        public int AreaRegionID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> RegionID { get; set; }
    
        public virtual dict_RegionInfo dict_RegionInfo { get; set; }
        public virtual master_AreaInfo master_AreaInfo { get; set; }
    }
}
