//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.Document.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_OKCInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public master_OKCInfo()
        {
            this.master_DistributorOKCInfo = new HashSet<master_DistributorOKCInfo>();
            this.master_ProductOKCPriceInfo = new HashSet<master_ProductOKCPriceInfo>();
        }
    
        public int OKCID { get; set; }
        public string OKCNO { get; set; }
        public Nullable<System.DateTime> OKCStart { get; set; }
        public Nullable<System.DateTime> OKCEnd { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<master_DistributorOKCInfo> master_DistributorOKCInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<master_ProductOKCPriceInfo> master_ProductOKCPriceInfo { get; set; }
    }
}
