//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.UserApply.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApply_ApplyBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserApply_ApplyBatch()
        {
            this.UserApply_UserApplyInfo = new HashSet<UserApply_UserApplyInfo>();
        }
    
        public System.Guid BatchID { get; set; }
        public string BatchName { get; set; }
        public string ApplyUser { get; set; }
        public string ApplyUserPhone { get; set; }
        public string ApplyUserEamil { get; set; }
        public Nullable<short> AuditStatus { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public string DistributorID { get; set; }
        public Nullable<short> Status { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserApply_UserApplyInfo> UserApply_UserApplyInfo { get; set; }
    }
}
