//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSOFT.DMS.UserApply.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApply_UserApplyInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserApply_UserApplyInfo()
        {
            this.UserApply_UserApplyAuthority = new HashSet<UserApply_UserApplyAuthority>();
        }
    
        public int UserApplyID { get; set; }
        public Nullable<System.Guid> BatchID { get; set; }
        public Nullable<int> UserChangeID { get; set; }
        public string UserApplyName { get; set; }
        public string UserApplyTelNumber { get; set; }
        public string UserApplyEmail { get; set; }
        public Nullable<short> UserApplyType { get; set; }
        public string DistributorIDList { get; set; }
        public Nullable<System.DateTime> UserApplyTime { get; set; }
        public Nullable<short> AuditStatus { get; set; }
        public string AuditRoleIDList { get; set; }
        public string AuditFalseReason { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        public virtual UserApply_ApplyBatch UserApply_ApplyBatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserApply_UserApplyAuthority> UserApply_UserApplyAuthority { get; set; }
    }
}
